export const UPDATE_LOBBY_LIST = 'UPDATE_LOBBY_LIST';

export const UPDATE_ROOM_LIST = 'UPDATE_ROOM_LIST';

export const UPDATE_ROOM_USERS = 'UPDATE_ROOM_USERS';

export const GET_ROOM_DETAILS = 'GET_ROOM_DETAILS';

export const START_GAME = 'START_GAME';
